### ISSUE TITLE
Flexget discover error

### ISSUE THREAD

**Issue by brothell** [srob650/pytvmaze#36]
Hello im using flexget and discover, everything was working fine but last few day im getting error:

`2016-04-23 14:18 CRITICAL task          get_tvshows     BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 274, in on_task_input
    entries = self.estimated(entries, estimation_mode)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 190, in estimated
    est_date = estimator.estimate(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 51, in estimate
    episode = lookup(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 520, in episode_lookup
    series = APITVMaze.series_lookup(session=session, only_cached=only_cached, **lookup_params)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 467, in series_lookup
    pytvmaze_show = get_show(**prepared_params)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 415, in get_show
    show_web_channel, embed=embed)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 467, in _get_show_by_search
    show = _get_show_with_qualifiers(show_name, qualifiers)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 444, in _get_show_with_qualifiers
    country = show.web_channel['country']['code'].lower()
TypeError: 'NoneType' object has no attribute '__getitem__'
 `
Could you please help me solve this :) Im using last version of flexget 1.2.521

**Comment by srob650** [comment]
I was waiting to see if liiight wanted to check this out since he is the one implementing pytvmaze in flexget, but after looking into it it I think I see the issue.  We're naively assuming that country code info exists for a given show.  I'll work on a fix but might not get to this before the weekend.

**Comment by liiight** [comment]
I must have missed this one till now

**Comment by srob650** [comment]
@liiight All good, looks to me like we just need to do a little checking to see if those values exist before trying to get them.  I might have time for this after work today.

**Comment by srob650** [comment]
The above commit should fix this @brothell - let me know!
