### ISSUE TITLE
Getting episodes for Fixer Upper does not work

### ISSUE THREAD

**Issue by kyleidex** [srob650/pytvmaze#45]
Doing this (3341 is the ID for the show Fixer Upper):
```
import pytvmaze
show = pytvmaze.get_show(maze_id=3341, embed='episodes')
```

Results in error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 374, in get_show
    return show_main_info(maze_id, embed=embed)
  File "/usr/local/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 563, in show_main_info
    return Show(q)
  File "/usr/local/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 56, in __init__
    self.populate(data)
  File "/usr/local/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 112, in populate
    self.episodes.append(Episode(episode))
  File "/usr/local/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 163, in __init__
    self.summary = _remove_tags(data.get('summary'))
  File "/usr/local/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 319, in _remove_tags
    return re.sub(r'<.*?>', '', text)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by srob650** [comment]
As of pytvmaze 2.x `get_show()` is now a method under `pytvamze.TVMaze()`.  As described in the readme, you should instead do this:

```python
import pytvmaze
tvm = pytvmaze.TVMaze()
show = tvm.get_show(maze_id=3341, embed='episodes')
```

This works on my machine.

**Comment by kylesezhi** [comment]
Thank you!
