### ISSUE TITLE
get_followed_shows throws error

### ISSUE THREAD

**Issue by faulander** [srob650/pytvmaze#46]
tvm = pytvmaze.TVMaze("harald.fauland@gmail.com", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
tvm.get_followed_shows()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\h.fauland\Downloads\_Projects\myTvOrganizer\venv\lib\site-packages\pytvmaze\tvmaze.py", line 739, in get_followed_shows
    return [FollowedShow(show) for show in q]
  File "C:\Users\h.fauland\Downloads\_Projects\myTvOrganizer\venv\lib\site-packages\pytvmaze\tvmaze.py", line 739, in <listcomp>
    return [FollowedShow(show) for show in q]
  File "C:\Users\h.fauland\Downloads\_Projects\myTvOrganizer\venv\lib\site-packages\pytvmaze\tvmaze.py", line 414, in __init__
    self.maze_id = data.get('show_id')
AttributeError: 'str' object has no attribute 'get'

**Comment by srob650** [comment]
Try using your TVMaze username instead of your email address.

**Comment by faulander** [comment]
i tried with username, user-id and email :(

**Comment by srob650** [comment]
Have you definitely followed shows on TVMaze?

**Comment by faulander** [comment]
for sure.

**Comment by srob650** [comment]
This is a TVMaze premium endpoint, do you pay for TVMaze Premium?

**Comment by faulander** [comment]
yes, i do.
