### ISSUE TITLE
show_akas fails to run

### ISSUE THREAD

**Issue by sirmarksalot** [srob650/pytvmaze#47]
show_akas fails to run

```from pytvmaze.tvmaze import *
>>> show_akas(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pytvmaze/tvmaze.py", line 383, in __repr__
    return '<AKA(name={name},country={country})>'.format(name=name, country=country)
NameError: name 'name' is not defined
```

**Comment by hxbt** [comment]
> show_akas fails to run
> 
> ```
> >>> show_akas(1)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "pytvmaze/tvmaze.py", line 383, in __repr__
>     return '<AKA(name={name},country={country})>'.format(name=name, country=country)
> NameError: name 'name' is not defined
> ```

Edit line 383 --> ... format(name=self.name, country=self.country)
